language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

env:
    - SYMFONY_VERSION=^2.7
    - SYMFONY_VERSION=^2.8
    - SYMFONY_VERSION=^3.1
    - SYMFONY_VERSION=^3.2
    - SYMFONY_VERSION=^3.3
    - SYMFONY_VERSION=^4.0

matrix:
  exclude:
    - php: '7.0'
      env: SYMFONY_VERSION=^4.0


before_script:
    - composer self-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer install --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    - bash <(curl -s https://codecov.io/bash)
